version: '3.9'
services:
  java_db:
    container_name: java_db
    image: 'postgres:latest'
    ports:
      - 5432:5432
    networks:
      - challenge
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: bankRed

  java_app:
    container_name: java_app
    image: account:1.0.0
    build:
      context: .
    ports:
      - 8082:8082
    networks:
      - challenge
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://java_db:5432/bankRed
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=postgrespw
    depends_on:
      - java_db

  java_app2:
    container_name: java_app2
    image: bank:1.0.0
    build:
      context: ../bank
    ports:
      - 8083:8083
    networks:
      - challenge
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://java_db:5432/bankRed
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=postgrespw

networks:
  challenge: